# Generated by Django 4.2.2 on 2023-06-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipes', '0002_recipe_picture_url_recipe_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisines',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisines_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
