# Generated by Django 4.2.2 on 2023-06-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipes', '0005_remove_recipe_cuisines'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisines_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myrecipes.cuisinetag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_tag',
            field=models.ManyToManyField(to='myrecipes.ingredienttag'),
        ),
    ]
