# Generated by Django 4.2.2 on 2023-06-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipes', '0006_recipe_cuisines_tag_recipe_ingredient_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisines_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myrecipes.cuisinetag'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myrecipes.ingredienttag'),
            preserve_default=False,
        ),
    ]
