# Generated by Django 4.2.2 on 2023-06-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipes', '0010_alter_recipe_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='image',
        ),
    ]
