# Generated by Django 4.2.2 on 2023-07-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipes', '0014_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
