# Generated by Django 4.2.2 on 2023-07-11 06:39

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipes', '0015_delete_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3StaticStorage, upload_to='recipe/'),
        ),
    ]
